### ISSUE TITLE
Crash with InvalidOperationException

### ISSUE THREAD

**Issue by StefanKulmer** [mikehadlow/AsmSpy#76]
When calling ".\AsmSpy.exe mydirectory" i got first a list of found references but it ends with an exception.

    :
    :
    Found reference PresentationCore 4.0.0.0
    Found reference PresentationFramework 4.0.0.0
    Found reference System 4.0.0.0
    Found reference System.ComponentModel.Composition 4.0.0.0
    Found reference System.Configuration 4.0.0.0
    Found reference System.Core 4.0.0.0
    Found reference System.Data 4.0.0.0
    Found reference System.Drawing 4.0.0.0
    Found reference System.IO.Compression.FileSystem 0.0.0.0
    Found reference System.Management 4.0.0.0
    Found reference System.Messaging 4.0.0.0
    Found reference System.Net 2.0.5.0
    Found reference System.Numerics 0.0.0.0
    Found reference System.Runtime.Remoting 2.0.0.0
    Found reference System.Runtime.Serialization 4.0.0.0
    Found reference System.ServiceModel 4.0.0.0
    Found reference System.ServiceModel.Discovery 4.0.0.0
    Found reference System.Threading.Tasks.Dataflow 4.5.24.0
    System.InvalidOperationException: Sequence contains more than one element
       at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
       at AsmSpy.Core.DependencyAnalyzer.ResolveNonFileReferences(DependencyAnalyzerResult result, ILogger logger)
       at AsmSpy.Core.DependencyAnalyzer.Analyze(IEnumerable`1 files, AppDomain appDomainWithBindingRedirects, ILogger logger, VisualizerOptions options, String rootFileName)
       at AsmSpy.CommandLine.Program.<>c__DisplayClass0_2.<Main>b__5(AppDomain appDomain)
       at AsmSpy.Core.ResultExtensions.<>c__DisplayClass1_0`2.<Map>b__0(A x)
       at AsmSpy.Core.ResultExtensions.Bind[A,B](Result`1 a, Func`2 func)
       at AsmSpy.Core.ResultExtensions.Map[A,B](Result`1 a, Func`2 func)
       at AsmSpy.CommandLine.Program.<>c__DisplayClass0_1.<Main>b__1(ValueTuple`2 x)
       at AsmSpy.Core.ResultExtensions.Bind[A,B](Result`1 a, Func`2 func)
       at AsmSpy.CommandLine.Program.<>c__DisplayClass0_0.<Main>b__0()

Sorry, that I can't post the assemblies, but that's enterprise code. It's a .NET Framework 4.6.1 application with including a WPF ui.

AsmSpy Version: 1.3.131

**Comment by StefanKulmer** [comment]
Occurs at AsmSpy.Core\DependencyAnalyzer.cs, Line 119.

    var alternativeVersion = result.Assemblies.Values
    	.Where(x => x.AssemblyName.Name == assembly.AssemblyName.Name)
    	.Where(x => x.ReflectionOnlyAssembly != null)   
    	.SingleOrDefault();

After the 2 Where operators there are 2 items left:
![2021-03-22 14_50_22-QuickWatch](https://user-images.githubusercontent.com/10090734/112000193-0a1ec300-8b1e-11eb-92cf-744b80864f03.png)

**Comment by mikehadlow** [comment]
Thanks for reporting this Stefan. I'll take a look.

**Comment by mikehadlow** [comment]
Hi Stefan. I've committed a fix that I hope should solve your issue, but without your assemblies to test with I can't be sure. Let me know if it works. Thanks again.

**Comment by StefanKulmer** [comment]
Hi Mike, thank you for your very fast fix. And thank for your great work at the AsmSpy tool!
